### ISSUE TITLE
Warning message from bowtie2/zlib in methylpy

### ISSUE THREAD

**Issue by coralzhang** [yupenghe/yupenghe.github.io#1] opened 2017-10-24 16:26 UTC
Here is what I used
` methylpy paired-end-pipeline \
	--read1-files $fqgz1 --read2-files $fqgz2 --sample AC10dpa \
	--forward-ref $fref --reverse-ref $rref --ref-fasta $reff \
	--num-procs 10 --sort-mem 51000000000 \
        --path-to-output="/WGBS" \
	--remove-clonal True \
	--path-to-picard="/picard/build/libs/"\
        >> $logname 2>&1
`
Here is the warning. 
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.

My file in gz format is about 4GB for each of the read pair. It has taken about 14 hours. I am not sure if it is that I am not using a good parameter that causes it to be so slow.

**Comment by yupenghe** [comment] 2017-10-24 17:01
Hi, it may be due to the bowtie2 option. Is your bowtie2 version more recent than 2.3.2? If not, I would encourage you to update it and try methylpy again. It may be the reason why the pipeline was slow. Thanks.

http://bowtie-bio.sourceforge.net/bowtie2/news.shtml

Version 2.3.2 - May 05, 2017
Now reports MREVERSE SAM flag for unaligned end when only one end of a pair aligns
Fixed issue where first character of some read names was omitted from SAM output when using tabbed input formats
Added --sam-no-qname-trunc option, which causes entire read name, including spaces, to be written to SAM output. This violates SAM specification, but can be useful in applications that immediately postprocess the SAM.
Fixed compilation error caused by pointer comparison issue in aligner_result.cpp
Removed termcap and readline dependencies introduced in v2.3.1
Fixed compilation issues caused by gzbuffer function when compiling with zlib v1.2.3.5 and earlier. Users compiling against these libraries will use the zlib default buffer size of 8Kb when decompressing read files.
Fixed issue that would cause Bowtie 2 hang when aligning FASTA inputs with more than one thread

**Comment by coralzhang** [comment] 2017-10-24 17:04
My bowtie2 is 2.3.3

**Comment by yupenghe** [comment] 2017-10-24 17:17
I see. Can you share the log file? Just want to check what the bottleneck
is.

**Comment by coralzhang** [comment] 2017-10-24 17:23
Sure. Here is the log I have as of now. It is still running. 

> Begin splitting reads for libA
Mon Oct 23 22:55:18 2017

Begin trimming reads for libA
Mon Oct 23 23:17:17 2017

Begin converting reads for libA
Mon Oct 23 23:21:04 2017

Begin Running Bowtie2 for libA
Mon Oct 23 23:22:54 2017

Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
70659869 reads; of these:
  70659869 (100.00%) were paired; of these:
    23874744 (33.79%) aligned concordantly 0 times
    17972324 (25.43%) aligned concordantly exactly 1 time
    28812801 (40.78%) aligned concordantly >1 times
66.21% overall alignment rate
Processing forward strand hits
Tue Oct 24 05:58:24 2017

Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
70659869 reads; of these:
  70659869 (100.00%) were paired; of these:
    24039294 (34.02%) aligned concordantly 0 times
    17917317 (25.36%) aligned concordantly exactly 1 time
    28703258 (40.62%) aligned concordantly >1 times
65.98% overall alignment rate
Processing reverse strand hits
Tue Oct 24 12:20:55 2017

Finding multimappers
Tue Oct 24 12:36:26 2017

[bam_sort_core] merging from 49 files...

It is the same file that I mentioned. 8GB gz format pairend data, which has run about 14-15 hours. It seems to be finishing now.

**Comment by yupenghe** [comment] 2017-10-24 17:46
It seems bowtie2 was one that took most of the run time.

I found this:
https://github.com/BenLangmead/bowtie2/issues/132

This issue seems to be resolved in 2.3.3.1 

Do you mind to give it a try? Just want to see if the warning is still there.

**Comment by coralzhang** [comment] 2017-10-24 17:47
Thanks for your suggestion. That was me.

**Comment by yupenghe** [comment] 2017-10-24 17:53
Ah, I did not notice that. Please let me know if 2.3.3.1 works for you. 

For WGBS processing, methylpy is a wrapper of the aligner (bowtie/bowtie2). If the aligner takes most of the run time, your best bet would be to use more processors and/or change the options passed to aligner using the --aligner-option parameter in methylpy. 

I will run a test run with similar amount of data on my end and see if it can give some hints.

**Comment by coralzhang** [comment] 2017-10-24 18:03
That is wonderful! I could really use some example testing time. ALso, I will try the alinger-option too.

**Comment by yupenghe** [comment] 2017-10-25 15:18
Here is the result on my end. Hope it helps. 

8 processors were used to process 86M read pairs. It took around 8.5h to get to the find_multimappers step (the last step in your log message) and 13.5h for the whole pipeline to finish.

Begin splitting reads for libA
Tue Oct 24 14:56:25 2017

Begin trimming reads for libA
Tue Oct 24 15:23:54 2017

Begin converting reads for libA
Tue Oct 24 15:30:40 2017

Begin Running Bowtie2 for libA
Tue Oct 24 15:36:58 2017

Processing forward strand hits
Tue Oct 24 19:16:01 2017

Processing reverse strand hits
Tue Oct 24 23:12:06 2017

Finding multimappers
Tue Oct 24 23:29:36 2017

There are 86118460 total input read pairs
Wed Oct 25 01:15:30 2017

There are 33907819 uniquely mapping read pairs, 39.3734618571 percent remaining
Wed Oct 25 01:15:30 2017

There are 20827015 non-clonal read pairs, 24.1841470458 percent remaining
Wed Oct 25 01:15:30 2017

Begin calling mCs
Wed Oct 25 01:15:30 2017

Begin flipping the strand of read 2
Wed Oct 25 01:15:30 2017

Input not indexed. Indexing...
Wed Oct 25 01:37:40 2017

Done
Wed Oct 25 03:24:26 2017

**Comment by yupenghe** [comment] 2017-10-25 16:23
I ran one test in which 86M read pairs (R1+R2 files take ~12g) were processed by methylpy using 10 processors. It took 8.5h to get to the find_multimappers step and ~12.5h to finish. bowtie2 took ~6.5h in the mapping step. I would suggest trying more processors (say 20) and to half the mapping runtime.

**Comment by coralzhang** [comment] 2017-10-25 20:37
That sounds about right with my testing statistics as well. By the way, Bowtie 2.3.3.1 does solve the warning problem. 
I have another question though.  I am wondering how should I turn off cutadapt if my reads are already clean.

**Comment by yupenghe** [comment] 2017-10-25 20:44
Great to hear. Adding "--trim-read False" will do.

**Comment by yupenghe** [comment] 2017-10-25 20:47
I will close this issue since it is resolved. If you have further questions regarding methylpy, please don't hesitate to open an issue under the methylpy repository.

**Closed by yupenghe** 2017-10-25 20:47 UTC

**Comment by coralzhang** [comment] 2017-10-25 20:52
Thank you very much!
